In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn import linear_model


In [2]:
# Lets consider a data used in linear model , where y = mx+c and we had two coloumns size and price for the houses.
#Now if we get the city constarint as well ?

# We know that machine learnig algorithms work beautifully on numbsers but not on words/sentaences.

# Solution 1 -> We can notate every string with the number.
# Problem -> It can make possible matching in between them althogh they are differnet.

# We call this Categorical Variables where the variables input data is str not number.

# There are two types of categorical variables.
'''
1. Nominal -> Who are indepedent from each other and any numeric consideration can violate the data fully.
like -> male/female/trans -> 1,2,3 -> data can present that -> male+female = trans from this. (1+2=3)

2. Ordinal -> who can be assigned a numerical value. like customer ratings.
like -> satisfied/neutal/dissatisfied -> 3,2,1
like -> high/medium/low -> 3,2,1

'''

'''ONE HOT ENCODING COMES HERE

We will use binary values , will create a dumm_variables = total no. of distinct inputs in nominal coloumn and,
assign 1 to the value on which we are working and 0 to rest all other dummy_variables.

We have pandas gift with us on this pandas.get_dummies(df.town)

'''

'ONE HOT ENCODING COMES HERE\n\nWe will use binary values , will create a dumm_variables = total no. of distinct inputs in nominal coloumn and,\nassign 1 to the value on which we are working and 0 to rest all other dummy_variables.\n\nWe have pandas gift with us on this pandas.get_dummies(df.town)\n\n'

In [3]:
data = pd.read_csv("homeprices.csv")
data

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [4]:
pd.get_dummies(data['town'])

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [ ]:
# we would like to store all this data in our original data, lets store this data in one df first

In [7]:
data1 = pd.get_dummies(data['town'])
data1

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [10]:
merge = pd.concat([data,data1],axis='columns')
merge

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [ ]:
# now town coloumn is no more of our use. we would like to drop it now

#one more thumb rule is that, we have 4 dummy_variales we have to drop one of them to avoid the problem of "Dummy variable trap"

# Dummy variable trap occurs with "Multi co-linaer" where one dummy variable can be derived from others 
#   and can mess with machine learning model

In [11]:
final = merge.drop(['town','west windsor'],axis='columns')
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [13]:
# sklearn linear regression is aware of dummy variable trap and will consider dropping it automatically.

# but it's a good practise to clean up the data on our own.

In [14]:
model = linear_model.LinearRegression()

In [15]:
#lets get the x and y variable ready for the work.

# lets figure out X in a special way.

In [16]:
x = final.drop(['price'],axis='columns')
x

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [18]:
y = final['price']
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [20]:
model.fit(x,y)


LinearRegression()

In [21]:
model.predict([[2800,0,1]])

C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [22]:
model.predict([[3400,0,0]])

C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [23]:
model.score(x,y)   #score 0 to 1 on accuracy of model

0.9573929037221873

In [24]:
###################################################################################################

In [25]:
'''Till here we have used dummy variable to work on, Now we will use ONE HOT ENCODING'''

'Till here we have used dummy variable to work on, Now we will use ONE HOT ENCODING'

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [29]:
dfle = data
dfle['town'] = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [30]:
#our data is ready the way we did with the dump variables, now we will make x,y for predict function.

In [60]:
X = dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [61]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [37]:
# but the problem of 2+1 =3 still exists with us, so we will launch other columns field as well.

#OneHotEncoder will help

In [62]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town',OneHotEncoder(),[0])],remainder='passthrough')
# remainder =  passthrough means thtat, 
#it will conactenate the left over coloumns with the transform coloumns otherwise it drops them

In [63]:
X = ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [64]:
X = X[:,1:]
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [65]:
model.fit(X,y)

LinearRegression()

In [67]:
model.predict([[1,0,2800]])

array([590775.63964739])

In [69]:
model.predict([[0,1,3400]])

array([681241.6684584])

In [70]:
model.score(X,y)

0.9573929037221873