In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
'''
Just now we discovered different methods of solving a Classifiaction Problem by :->

1. Logistic Regression 
2. Decision Tree
3. SVM
4. Random Forest

But which one is best ???? Who will tell this ??

Option 1 -> Train 100% of the data using all the algorithms individually, and find the best one by testing the data on the
            same set, but that is not a good approach, i.e repetitive

Option 2 -> Train x% of data for training and (100-x)% data for the testing, uhmmmm, that's also has a limitation, 
            we are not sure if some part is data is left fully untrained, and finding values on that is meaningless.
            
Option 3 -> K fold cross
            In this method, suppose there are 100 records avaialble, a set of samples will used to train the model one by one.
            i.e 1-20, 21-40, 41-60, 61-80, 81-100.
            
            Once the score is out for all of them, we will calculate the mean of these scores.
'''

"\nJust now we discovered different methods of solving a Classifiaction Problem by :->\n\n1. Logistic Regression \n2. Decision Tree\n3. SVM\n4. Random Forest\n\nBut which one is best ???? Who will tell this ??\n\nOption 1 -> Train 100% of the data using all the algorithms individually, and find the best one by testing the data on the\n            same set, but that is not a good approach, i.e repetitive\n\nOption 2 -> Train x% of data for training and (100-x)% data for the testing, uhmmmm, that's also has a limitation, \n            we are not sure if some part is data is left fully untrained, and finding values on that is meaningless.\n            \nOption 3 -> K fold cross\n            In this method, suppose there are 100 records avaialble, a set of samples will used to train the model one by one.\n            i.e 1-20, 21-40, 41-60, 61-80, 81-100.\n            \n            Once the score is out for all of them, we will calculate the mean of these scores.\n"

In [5]:
from sklearn.datasets import load_digits
data = load_digits()
data

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.data,data.target,test_size=0.3)

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [38]:
model1 = LogisticRegression()
model1.fit(x_train,y_train)
model1.score(x_test,y_test)

C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [39]:
model2 = DecisionTreeClassifier()
model2.fit(x_train,y_train)
model2.score(x_test,y_test)

0.8574074074074074

In [40]:
model3 = SVC()
model3.fit(x_train,y_train)
model3.score(x_test,y_test)

0.9851851851851852

In [41]:
model4 = RandomForestClassifier()
model4.fit(x_train,y_train)
model4.score(x_test,y_test)

0.9703703703703703

In [44]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [45]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [46]:
def score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [47]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [50]:
scores_l=[]
scores_d=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(data.data):
    x_train,x_test,y_train,y_test= data.data[train_index],data.data[test_index],data.target[train_index],data.target[test_index]
    scores_l.append(score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_d.append(score(DecisionTreeClassifier(),x_train,x_test,y_train,y_test))
    scores_svm.append(score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

In [55]:
print(scores_l)
print(scores_d)
print(scores_svm)
print(scores_rf)

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
[0.7846410684474123, 0.8163606010016694, 0.7813021702838063]
[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
[0.9298831385642737, 0.9549248747913188, 0.9215358931552587]


In [56]:
from sklearn.model_selection import cross_val_score

In [59]:
cross_val_score(LogisticRegression(),data.data,data.target)

C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [61]:
cross_val_score(DecisionTreeClassifier(),data.data,data.target)

array([0.77222222, 0.70833333, 0.79387187, 0.83286908, 0.7994429 ])

In [63]:
cross_val_score(SVC(),data.data,data.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [64]:
cross_val_score(RandomForestClassifier(),data.data,data.target)

array([0.93888889, 0.9       , 0.9637883 , 0.9637883 , 0.91643454])